services:
  - type: web
    name: agriscope-backend-flask
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GOOGLE_SERVICE_ACCOUNT_KEY
        sync: false  # Set this in Render dashboard
